commenting failing step

diff --git a/.github/workflows/15-matrices.yaml b/.github/workflows/15-matrices.yaml
--- a/.github/workflows/15-matrices.yaml
+++ b/.github/workflows/15-matrices.yaml
@@ -24,9 +24,9 @@ jobs:
         uses: actions/setup-node@v2
         with:
           node-version: ${{ matrix.node }}
-      - name: Fail if experimental
-        if: ${{ matrix.tag == 'experimental' }}
-        run: exit 1
+      # - name: Fail if experimental
+      #   if: ${{ matrix.tag == 'experimental' }}
+      #   run: exit 1
       - name: Perform some tests
         run: echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node }}"
       - name: Upload test results
